dist: trusty
sudo: false
language: generic
branches:
  only:
    - master
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive-full
addons:
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-lang-greek
    - latex-xcolor
install:
  - conda env create --quiet --file build/environment.yml
  - conda activate manubot
  - pip install panflute
  - pip install pandocfilters
  - pip install pandoc-img-glob
  - sh ci/pandoc-chemfig.sh
script:
  - BUILD_HTML=true sh build/build.sh
  - sh build/build.sh
cache:
  directories:
    - ci/cache
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    sh ci/deploy.sh
